export const GET_ALL_POKEMON_REQUEST = "GET_ALL_POKEMON_REQUEST";
export const GET_ALL_POKEMON_SUCCESS = "GET_ALL_POKEMON_SUCCESS";
export const GET_ALL_POKEMON_FAIL = "GET_ALL_POKEMON_FAIL";

export const GET_POKEMON_BY_NUMBER_REQUEST = "GET_POKEMON_BY_NUMBER_REQUEST";
export const GET_POKEMON_BY_NUMBER_SUCCESS = "GET_POKEMON_BY_NUMBER_SUCCESS";
export const GET_POKEMON_BY_NUMBER_FAIL = "GET_POKEMON_BY_NUMBER_FAIL";

export const GET_POKEMON_BY_ID_REQUEST = "GET_POKEMON_BY_ID_REQUEST";
export const GET_POKEMON_BY_ID_SUCCESS = "GET_POKEMON_BY_ID_SUCCESS";
export const GET_POKEMON_BY_ID_FAIL = "GET_POKEMON_BY_ID_FAIL";
